apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
  labels:
    app: {{ .Release.Name }}-ds
    component: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ds
      name: {{ .Release.Name }}-ds
    spec:
      serviceAccount: {{ .Release.Name }}-sa
      hostPID: true
      containers:
      - name: enforcer
        image: "{{ .Values.global.imageCredentials.registry }}/{{ .Values.enforcer.image }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: "{{ .Values.global.image.pullPolicy }}"
        securityContext:
          privileged: true
        env:
        - name: AQUA_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-enforcer-token
              key: token
        - name: AQUA_SERVER
          value: {{ .Release.Name }}-gateway-svc:3622
        - name: AQUA_LOGICAL_NAME
          value: {{ .Release.Name }}-eks
        - name: RESTART_CONTAINERS
          value: "no"
        - name: AQUA_RUN_WATCHER
          value: "yes"
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /dev
          name: dev
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/etc
          name: etc
          readOnly: true
        - mountPath: /host/opt/aquasec
          name: aquasec
          readOnly: true
        - mountPath: /opt/aquasec/tmp
          name: aquasec-tmp
        - mountPath: /opt/aquasec/audit
          name: aquasec-audit
      volumes:
      - name: var-run
        hostPath:
          path: /var/run
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: aquasec
        hostPath:
          path: /var/lib/aquasec
      - name: aquasec-tmp
        hostPath:
          path: /var/lib/aquasec/tmp
      - name: aquasec-audit
        hostPath:
          path: /var/lib/aquasec/audit
