{{- if not .Values.global.db.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-svc
  labels:
    app: {{ .Release.Name }}-database
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - port: {{ default 5432 .Values.db.service.servicePort }}
{{- end }}
