{{- if .Values.global.db.external.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-password
  annotations:
    "helm.sh/hook": pre-install
  labels:
    secretType: aquaSecurity
type: Opaque
data:
  db-password: {{ .Values.global.db.external.password | b64enc | quote }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-password
  annotations:
    "helm.sh/hook": pre-install
  labels:
    secretType: aquaSecurity
type: Opaque
data:
  db-password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}