---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-database-pvc
  annotations:
    "helm.sh/hook": pre-install
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.db.internal.pvsize | quote }}
  

