---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  app.kubernetes.io/name: "{{ .Release.Name }}"
  labels:
    secretType: aquaSecurity
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
