apiVersion: v1
description: Aqua Container Security Platform
name: aqua
appVersion: "4.2"
version: 4.2.0
home: aquasec.com
keywords:
- aquasec
- aqua
- aqua security
- container
- security
- csp
maintainers:
- email: maintainers@aquasec.com
  name: maintainers
